/**
 * Bundle the vite single-file build of the MCP app view into the serverless
 * function. Vercel functions have no reliable runtime filesystem for build
 * artifacts, so instead of `fs.readFile`-ing dist/ at request time, we emit the
 * built HTML as a string constant that the MCP route imports — guaranteeing it
 * lands inside the deployed function bundle.
 *
 * Run after `vite build` (see the `build` / `dev` scripts). The output is
 * generated, gitignored, and rewritten on every build.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";

const SRC = "dist/ares-explorer.html";
const OUT = "app/api/mcp/ares-explorer-html.ts";

const html = readFileSync(SRC, "utf8");

// JSON.stringify yields a valid, fully-escaped JS string literal regardless of
// what the HTML/JS/CSS payload contains (backticks, ${}, quotes, newlines).
const contents =
  "// AUTO-GENERATED by scripts/inline-html.mjs — do not edit. Run `npm run inline`.\n" +
  `export const ARES_EXPLORER_HTML = ${JSON.stringify(html)};\n`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, contents);

console.log(`inlined ${SRC} (${html.length} bytes) → ${OUT}`);
